services:
  - type: web
    name: devops-pipeline
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: AWS_REGION
        value: us-west-2
      - key: AWS_ACCOUNT_ID
        value: "123456789012"
      - key: EKS_CLUSTER_NAME
        value: production-cluster
    autoDeploy: true
    branch: main
    rootDir: .
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCPUPercent: 80
